### PR TITLE
ENH: add active report

### PR DESCRIPTION
**Pull request by tangkong**
## Description
Adds a basic active report, autogenerated from a PreparedProcedureFile

Does a lot of refactoring, extracting methods into (hopefully) more generally useful functions.
Moves the `AnyDataclass` type hint into the type_hints file.  

## Motivation and Context
We want active reports! 

## How Has This Been Tested?
interactively 

## Where Has This Been Documented?
This PR makes documentation!

### CODE REVIEW

**Comment by ZLLentz** [comment]
There isn't much to scrutinize here, the refactors are sensible.
Is there any easy way for me to run and generate a report to look at?

**Comment by ZLLentz** [comment]
I can't seem to get an active report to run, I'm met with this exception:
```
Traceback (most recent call last):
  File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.7.1/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.7.1/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cds/home/z/zlentz/github/atef/atef/__main__.py", line 3, in <module>
    main()
  File "/cds/home/z/zlentz/github/atef/atef/bin/main.py", line 99, in main
    func(**kwargs)
  File "/cds/home/z/zlentz/github/atef/atef/bin/config.py", line 87, in main
    app.exec()
  File "/cds/home/z/zlentz/github/atef/atef/widgets/config/window.py", line 304, in print_report
    run_tree.print_report()
  File "/cds/home/z/zlentz/github/atef/atef/widgets/config/window.py", line 549, in print_report
    doc.create_report()
  File "/cds/home/z/zlentz/github/atef/atef/report.py", line 854, in create_report
    self.build_step_page(story, step)
  File "/cds/home/z/zlentz/github/atef/atef/report.py", line 938, in build_step_page
    story.append(Paragraph(step.origin.description))
  File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.7.1/lib/python3.9/site-packages/reportlab/platypus/paragraph.py", line 1801, in __init__
    self._setup(text, style, bulletText or getattr(style,'bulletText',None), frags, cleanBlockQuotedText)
  File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.7.1/lib/python3.9/site-packages/reportlab/platypus/paragraph.py", line 1819, in _setup
    text = cleaner(text)
  File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.7.1/lib/python3.9/site-packages/reportlab/platypus/paragraph.py", line 135, in cleanBlockQuotedText
    L=list(filter(truth,list(map(_lineClean, split(text, '\n')))))
  File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.7.1/lib/python3.9/site-packages/reportlab/platypus/paragraph.py", line 92, in split
    return [uword for uword in (_wsc_re_split(text) if delim is None and u'\xa0' in text else text.split(delim))]
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by ZLLentz** [comment]
I figured it out, my DescriptionStep had no description, whoops. I thought I put one it but I was wrong.

**Comment by tangkong** [comment]
Whoops.  Either way though I should be able to handle those cases better.  We don't imply the description is necessary anywhere else.  pushed a quick fix

**Comment by ZLLentz** [comment]
Here are some nonsense reports I generated. I used a file with a description step, a step that sets a known beamline PV already at 1 to 1, and a step that checks that it is indeed at 1. All of the fields have useless button mash names or asdf because I just wanted to see the formats.

I think these are pretty good.

No test has been run: [asdf.pdf](https://github.com/pcdshub/atef/files/11401419/asdf.pdf)
Running failure (permissions): [asdf2.pdf](https://github.com/pcdshub/atef/files/11401420/asdf2.pdf)
Everything succeeded: [asdf3.pdf](https://github.com/pcdshub/atef/files/11401421/asdf3.pdf)

The only oddity I found is that I could get not the root step to be marked as success. I ran the test via the GUI.
The report correctly reported that the UI did not mark the root step as completed.

**Comment by tangkong** [comment]
Hm, there's some finagling to do with the results.  I could get the root step to mark itself as successful, but only after clicking the run button on the root page.  The results from the subpages probably aren't being read unless explicitly asked for.  

I'll tackle that in a separate PR.  I've been wanting to touch up how the result icons update.  

Aside from that I tried to limit the size of Result readouts, since they have the possibility of making tables way too wide

**Comment by ZLLentz** [comment]
Sounds good to me!
Note that I was clicking the root run button in the example outputs above

**Pull request merged**
